# Site settings
title: My Little Website
tagline: "Changing the world, one uninspired quote at a time"
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
profileimg: /img/profile.jpg # change this to YOUR picture
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername

# Contact
phone: "916-276-1044" # This is my real number. You should text me.
email: "hello@garrettboatman.com" # This is my real email address. Please don't email me.
first_name: "Garrett"
last_name: "Boatman"
# Use this for production
markdown: kramdown
sass:
   sass_dir: _sass
   style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
